---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[apt::default]
      - recipe[consul::default]
      - recipe[consul-services::cron]
      - recipe[consul-services::apache2]
      - recipe[consul-services::mysql]
      - recipe[consul-services::postgres]
      - recipe[consul-services::wordpress]
      - recipe[consul-services::lsyncd]
    attributes:
      consul:
        service_user: 'root'
        service_group: 'root'
